### PR TITLE
chrome看优酷高清

### PR DESCRIPTION
**Pull request by fadying**
chrome看优酷至少能看个高清

### CODE REVIEW

**Comment by fadying** [comment]
只能看6分钟。。

**Comment by zythum** [comment]
这个是切片的。需要播放器支持切片。这个比较复杂。等朱一有时间折腾的时候搞。播放器项目在这里。 https://github.com/zythum/mamaplayer

**Comment by fadying** [comment]
我试图使用videojs的[hls插件](https://github.com/videojs/videojs-contrib-hls)来使chrome播放优酷的超清m3u8格式，但是这个插件会有`Access-Control-Allow-Origin`这个问题，这个路子是不是不行啊

**Comment by zythum** [comment]
@fadying 你很能折腾。官方有说明这个问题
Unlike a native HLS implementation, the HLS tech has to comply with the browser's security policies. That means that all the files that make up the stream must be served from the same domain as the page hosting the video player or from a server that has appropriate CORS headers configured. Easy instructions are available for popular webservers and most CDNs should have no trouble turning CORS on for your account.

这个方式只能在视频和页面同域名的情况下才可以。

**Pull request closed without merging**
